### PR TITLE
Fix regression: Support first run on tag-less repos

### LINKED ISSUE #28: Regression: action fails if no tags yet
It looks like there is a regression of #18 

```
Run fregante/daily-version-action@v2
  with:
  env:
    DIRECTORY: distribution
Error: Error Command failed: git fetch --depth=1 origin refs/tags/*:refs/tags/*
````

### PR DESCRIPTION
**Pull request by fregante**
- Closes https://github.com/fregante/daily-version-action/issues/28
- Same as #19

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ async function init() {
 		'--depth=1',
 		'origin',
 		'refs/tags/*:refs/tags/*',
-	]);
+	]).catch(() => {}); // It might be a new repo #18
```
Comment (fregante) [inline index.js:24]: Mistakenly dropped in https://github.com/fregante/daily-version-action/pull/20
